###############################################################################
# Custom Rules
################################################################################

SRC  = $(shell egrep -l '^[^%]*\\begin\{document\}' *.tex)
TRG  = $(SRC:%.tex=%.pdf)

all: $(TRG)
.PHONY: $(TRG) clean rolling

################################################################################
# Latexmk Rules
################################################################################
# -pdf: Generate pdf version of document using pdflatex.
#
# -bibtex: When the source file uses bbl files for bibliography, run bibtex or
#  biber as needed to regenerate the bbl files.
#
#  -C: Clean up (remove) all regeneratable files generated by latex and bibtex
#  or biber.
################################################################################

rolling: $(SRC)
	latexmk -pvc -pdf -bibtex -interaction=nonstopmode $(SRC)

$(TRG): $(SRC) *.tex
	latexmk -pdf -bibtex $(SRC)
	rm -f *.aux *.fls *.log *.out *.fdb_latexmk

clean:
	latexmk -C -bibtex

